### ISSUE TITLE
Theme setting to darken focused form colors

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-atom-ui#43]
All forms have an snow-inspired color effect when focused by using a light background color and a dark foreground color for the text.
As mentioned in another issue this could interfere with some users due to the contrast change.
A theme setting should be added to use a darker focus color.

![ghi-43-scrcast-before](https://cloud.githubusercontent.com/assets/7836623/20311958/f694259c-ab51-11e6-8c2e-cf9dae01b774.gif)

**Comment by arcticicestudio** [comment]
Added a theme setting to use a darker form-focusing background color.

![ghi-43-scrot-theme-setting](https://cloud.githubusercontent.com/assets/7836623/20313180/636b4f48-ab56-11e6-8502-ad99f163c94b.png)

![ghi-43-scrcast-after](https://cloud.githubusercontent.com/assets/7836623/20313189/6c044736-ab56-11e6-9c33-c579e7d6dfd4.gif)

**Comment by arcticicestudio** [comment]
Released in :package: version [0.8.0](https://github.com/arcticicestudio/nord-atom-ui/releases/tag/v0.8.0)

**Comment by KillerCars** [comment]
Atom version
1.28.2 x64

Platform Details
MacOS 10.13.5

This setting does not work for me (and hasn't worked for a long time). Whether darkerFormFocusEffect is set to true or false, forms still have the snow-inspired color effect.
Also, when performing a global search (command + shift + f), the first two fields have a dark font, which is visible against the light background, but the third field uses a light font, which is why I wanted to switch on darker form fields in the first place.

![screen shot 2018-07-19 at 14 36 58](https://user-images.githubusercontent.com/39372181/42945823-49bfa9d0-8b61-11e8-92fb-ad87945152b8.png)
![screen shot 2018-07-19 at 14 37 08](https://user-images.githubusercontent.com/39372181/42945825-49e4631a-8b61-11e8-9314-1b2288d320fe.png)

Is this a known issue?
